### PR TITLE
ENH: Updates to team compass

### PR DESCRIPTION
**Pull request by trallard**
This PR adds the following changes:

- :construction_worker: Updates to CI - make the messages more human readable
- :construction_worker: Add HTML proofer - ensure we do not have broken links in our site
- :memo: Add the following sections to the compass:
  - Contributing - instructions to set the development env for the compass
  - Add code of conduct (basically the same one from the repo)
  - Placeholder for the roadmap for @isabela-pf  😉
- 💅🏽  Also made some stylistic changes - mostly changing the font for one that has ligatures and make some colour changes
- Deploy to Netlify:
  - Adds Pipfile to keep the versions consistent - only jupyter book atm
  - Update nox commands - one for CI one for local development
  - Adds previews (see PR comment here)

🙏🏽  I am sorry for sending so many changes in a single PR

### CODE REVIEW

**Comment by trallard** [comment]
Once this is merged - the site should be available at <https://jupyter-a11y.netlify.app>

**Comment by gabalafou** [comment]
The site preview looks really great! 

I have two potential concerns, but maybe it's because I lack context:

- When I see "contribute to this project" page, it makes me think that contributing to the project = working on the website. Perhaps the page should be retitled "Contribute to this website"? But then at some point, I imagine we want to write about how to contribute to the overall project, meaning a11y in JupyterLab, is that correct? 
- If I were to come to this website without much context, one of the first links I would probably click is "Learn more about the CZI grant," which takes me to the application, which is pretty big. Would it be useful to have a one-paragraph blurb on the index.html page at the top that summarizes what this website is, who it's for, and who the major players are? Again, apologies if I'm lacking context about where this site will live, how people will find it, etc.

**Comment by trallard** [comment]
>When I see "contribute to this project" page, it makes me think that contributing to the project = working on the website. Perhaps the page should be retitled "Contribute to this website"? But then at some point, I imagine we want to write about how to contribute to the overall project, meaning a11y in JupyterLab, is that correct?

this is correct - we want to either write broader contribution guidelines for the whole initiative and point to actionable items folks can help with

> If I were to come to this website without much context, one of the first links I would probably click is "Learn more about the CZI grant," which takes me to the application, which is pretty big. Would it be useful to have a one-paragraph blurb on the index.html page at the top that summarizes what this website is, who it's for, and who the major players are? Again, apologies if I'm lacking context about where this site will live, how people will find it, etc.

This makes sense - and would definitely benefit whoever stumbles with the site by chance - @gabalafou @isabela-pf  is this something any of you could add to the compass in my absence?

**Comment by gabalafou** [comment]
I gave it a quick try. I'm sure the word choice, language, and tone need to be workshopped:

Welcome! You have arrived at the homepage of an exciting project. We are Quansight Labs and we have an ambitious goal—to make JupyterLab accessible—and we would love your input and help. 

In mid 2021, Quansight Labs received a two-year grant from the Chan Zuckerberg Initiative to work with Project Jupyter on making JupyterLab accessible. This website is part of our effort to stay transparent, accountable, and open to the community and the broader public.

**Pull request merged**
