### PR TITLE
Update roadmap November 11

### LINKED ISSUE #2: Develop a public roadmap for a11y improvements
## Summary

- There is an [existing GH project](https://github.com/orgs/jupyterlab/projects/1) that Isabela, Tony, et. al have put together over time to track issues and work-related to a11y on Jupyterlab.
- There is however no canonical roadmap to refer to and to track work and goals against.

## Acceptance Criteria

- [ ] The roadmap is published and shared with the broader community
- [ ] Write a blogpost to announce the creation of the roadmap 

## Tasks to complete

- [ ] #33
- [ ] #34
- [ ] #35
- [ ] #36

### PR DESCRIPTION
**Pull request by isabela-pf**
As discussed in #2 and the weekly update at #49, here is a draft for the current roadmap. It should capture everything in labelled on the 6 months milestone while reflecting what we are currently working on.

Feedback on form and content very welcome! Let me know if you have any questions.

___

Fixes #2

### CODE REVIEW

**Comment by isabela-pf** [comment]
Feedback from the November 17 JupyterLab accessibility meeting:

- Linking to issues might be nice. Which issues make sense (we have duplicate issues across some repositories)?
- Are there repository labels/tags that make sense to link to? (Especially if it's not a one-issue problem.)
- Add another page "changelog" that lists what we have completed when things get moved off the roadmap.

**Comment by isabela-pf** [comment]
Feedback from the November 18 JupyterHub/BinderHub community meeting:

This community didn't make requests, they asked questions that I found very important. They asked things like
- Isn't this all JupyterLab? This all looks like JupyterLab.
- Documentation seems like it's not in the scope of the grant, but would you consider it as a part of community engagement because it helps everyone?
- How do we get started understanding accessibility? What can we do to start trying to make things accessible now?

Even though these were questions, I think they all correlate to actions I'd like to take with the roadmap. - This roadmap shows near future things and JupyterLab is a year-one focus. But this should call out ways in which that is not the case. The grant explicitly includes non-JupyterLab contributions.
- Documentation is in the scope of the grant, so we should similarly list this like above.
- A related document might be a "crash course" in accessibility (discussed in #61 at today's check in meeting). We don't want people to feel excluded or like this is something they can't understand. Link this in the roadmap.

I think some of this could be solved by adding an `Overall goals` section to this document that lists the kind of `1. make JupyterLab accessible 2. build automated accessibility tests that are compatible with Jupyter tools 3. document what we've learned/best practices for this in this ecosystem 4. share with other projects and help them start implementing them` plan we describe in the grant. 

---

On a related note, we talked about sharing this roadmap in meetings in #61 and @gabalafou and @tonyfast noticed that there seemed to be not great feelings about seeing this work.

**Comment by isabela-pf** [comment]
I know we were discussing putting this roadmap on the [jupyter/accessibility repo](https://github.com/jupyter/accessibility), but I figured since we started review here it would be good to continue discussions here. Once we think this is ready to be posted, I can put in a PR to jupyter/accessibility.

I also left some areas with placeholders of content I think we want but don't have yet, like the completed tasks "changelog" and the getting started in accessibility.

**Review by trallard — APPROVED** [review]
LGTM - so will approve and merge

**Pull request merged**
